services:
  # Java Backend Service (PlayMetric API)
  java-api:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    container_name: playmetric-java-api
    ports:
      - "8080:8080"
    networks:
      - playmetric-network
    restart: unless-stopped

  # Python AI Analytics Service (PAIME)
  python-ai:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: paime-analytics
    ports:
      - "8000:8000"  # FastAPI API
      - "8050:8050"  # Dash Dashboard
    environment:
      - MONGODB_URI=mongodb://mongo:gSFyjoeBNGrWpElewAfFLzloUYmSyqRm@gondola.proxy.rlwy.net:21458
      - DATABASE_NAME=playmetric
    depends_on:
      - java-api
    networks:
      - playmetric-network
    restart: unless-stopped

networks:
  playmetric-network:
    driver: bridge
