spring:
  profiles:
    active: local
  data:
    mongodb:
      database: playmetric
      auto-index-creation: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017

---
spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${MONGODB_URI}  # Will be set in cloud environment
