spring:
  data:
    mongodb:
      # WARNING: this file contains hardcoded credentials per your request. These are sensitive values.
      # The repository now includes the Railway Mongo connection string you provided.
      # If you want to revert to environment-based configuration, replace this with:
      # uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/playmetric}
      uri: "mongodb://mongo:gSFyjoeBNGrWpElewAfFLzloUYmSyqRm@gondola.proxy.rlwy.net:21458/playmetric?authSource=admin"

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.playmetric: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
