spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: playmetric
      authentication-database: admin

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.playmetric: INFO
