spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/playmetric}
      # If you prefer separate properties locally, the default above points to the docker-compose MongoDB
      # In production (Railway) set SPRING_DATA_MONGODB_URI to the connection string provided by Railway

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.playmetric: INFO
